Piece
const PieceType Piece::name
Referenced by getName.
const Color Piece::color
Referenced by Bishop::generateMoves, King::generateMoves, Knight::generateMoves, Pawn::generateMoves, Queen::generateMoves, Rook::generateMoves, getColor, isUnderAttack.
int Piece::moveCount
Referenced by Pawn::generateMoves, getCount, Piece, PieceMoved.
vector<Point> Piece::movesAvailable
Referenced by addMove, Bishop::generateMoves, King::generateMoves, Knight::generateMoves, Pawn::generateMoves, Queen::generateMoves, Rook::generateMoves, getAvailableMoves, isMoveLegal, numberMoves.
vector<Piece*> Piece::pawnLocation
Referenced by Pawn::AddenPassant, Pawn::enPassant.
Cell * Piece::cell
Referenced by Bishop::generateMoves, King::generateMoves, Knight::generateMoves, Pawn::generateMoves, Queen::generateMoves, Rook::generateMoves, isUnderAttack, setCellArray.
vector< Piece * > Piece::pieces
Referenced by getPieces, Piece.
Piece::Piece(Color m_color, PieceType name)
References moveCount, pieces.
Color Piece::getColor()
References color.
PieceType Piece::getName()
References name.
void Piece::PieceMoved()
References moveCount.
Referenced by Board::movePiece.
vector< Point > Piece::getAvailableMoves()
References movesAvailable.
int Piece::inLimits(Point checkPos)
References Point::x, Point::y.
Referenced by Bishop::generateMoves, King::generateMoves, Knight::generateMoves, Pawn::generateMoves, Queen::generateMoves, Rook::generateMoves, isUnderAttack.
void Piece::generateMoves(Point currentPos)
int Piece::isMoveLegal(Point newPos)
References movesAvailable, Point::x, Point::y.
bool Piece::isUnderAttack(Point currentPos)
References bishop, black, cell, color, GRID, inLimits, knight, pawn, queen, rook, white, Point::x, Point::y.
void Piece::addMove(Point pos)
References movesAvailable, Point::x, Point::y.
int Piece::numberMoves()
References movesAvailable.
int Piece::getCount()
References moveCount.
Direction Piece::getPawnDirection()
bool Piece::enPassant(Piece *ptr)
void Piece::AddenPassant(Piece *ptr)
vector< Point > Piece::getPossibleMoves()
void Piece::setCellArray(Cell *m_cell)
References cell.
Referenced by Board::Board.
vector< Piece * > Piece::getPieces()
References pieces.
Referenced by Board::~Board.
void Piece::clearPieces()
Referenced by Board::~Board.