.TH "Cell" 3 "Thu May 27 2021" "Version 2.0" "Chess-OOP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cell
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cell\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCell\fP ()"
.br
.ti -1c
.RI "void \fBsetNull\fP ()"
.br
.ti -1c
.RI "void \fBsetPiece\fP (\fBPiece\fP *m_piece)"
.br
.ti -1c
.RI "\fBPiece\fP * \fBgetPiece\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBPiece\fP * \fBpiece\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Cell::Cell ()"

.SH "Member Function Documentation"
.PP 
.SS "\fBPiece\fP * Cell::getPiece ()"

.SS "void Cell::setNull ()"

.SS "void Cell::setPiece (\fBPiece\fP * m_piece)"

.SH "Member Data Documentation"
.PP 
.SS "\fBPiece\fP* Cell::piece\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Chess-OOP from the source code\&.
