.TH "Detail" 3 "Thu May 27 2021" "Version 2.0" "Chess-OOP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Detail
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <enums_data\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "\fBColor\fP \fBcolor\fP"
.br
.ti -1c
.RI "\fBPieceType\fP \fBname\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBColor\fP Detail::color"

.SS "\fBPieceType\fP Detail::name"

.SS "int Detail::x"

.SS "int Detail::y"


.SH "Author"
.PP 
Generated automatically by Doxygen for Chess-OOP from the source code\&.
