.TH "enums_data.h" 3 "Thu May 27 2021" "Version 2.0" "Chess-OOP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
enums_data.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBPoint\fP"
.br
.ti -1c
.RI "struct \fBDetail\fP"
.br
.ti -1c
.RI "struct \fBMoves\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBPieceType\fP { \fBking\fP, \fBqueen\fP, \fBbishop\fP, \fBknight\fP, \fBrook\fP, \fBpawn\fP }"
.br
.ti -1c
.RI "enum \fBColor\fP { \fBblack\fP, \fBwhite\fP }"
.br
.ti -1c
.RI "enum \fBStatus\fP { \fBalive\fP, \fBdead\fP }"
.br
.ti -1c
.RI "enum \fBConnectionType\fP { \fBhost\fP, \fBclient\fP }"
.br
.ti -1c
.RI "enum \fBDirection\fP { \fBup\fP, \fBdown\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBColor\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIblack \fP\fP
.TP
\fB\fIwhite \fP\fP
.SS "enum \fBConnectionType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIhost \fP\fP
.TP
\fB\fIclient \fP\fP
.SS "enum \fBDirection\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIup \fP\fP
.TP
\fB\fIdown \fP\fP
.SS "enum \fBPieceType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIking \fP\fP
.TP
\fB\fIqueen \fP\fP
.TP
\fB\fIbishop \fP\fP
.TP
\fB\fIknight \fP\fP
.TP
\fB\fIrook \fP\fP
.TP
\fB\fIpawn \fP\fP
.SS "enum \fBStatus\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIalive \fP\fP
.TP
\fB\fIdead \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Chess-OOP from the source code\&.
