.TH "Gui" 3 "Thu May 27 2021" "Version 2.0" "Chess-OOP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Gui
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gui\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGui\fP ()"
.br
.ti -1c
.RI "\fBGui\fP (const \fBConnectionType\fP type, string ip)"
.br
.ti -1c
.RI "\fB~Gui\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Gui::Gui ()"

.SS "Gui::Gui (const \fBConnectionType\fP type, string ip)"

.SS "Gui::~Gui ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Chess-OOP from the source code\&.
