.TH "king.cpp" 3 "Thu May 27 2021" "Version 2.0" "Chess-OOP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
king.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'enums_data\&.h'\fP
.br
\fC#include 'cell\&.h'\fP
.br
\fC#include 'piece\&.h'\fP
.br
\fC#include 'king\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGRID\fP   8"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define GRID   8"

.SH "Author"
.PP 
Generated automatically by Doxygen for Chess-OOP from the source code\&.
