.TH "Network" 3 "Thu May 27 2021" "Version 2.0" "Chess-OOP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Network
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <network\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNetwork\fP (string s)"
.br
.ti -1c
.RI "\fBNetwork\fP ()"
.br
.ti -1c
.RI "void \fBsend\fP (int a, int b, int c, int d)"
.br
.ti -1c
.RI "void \fBsend\fP (int a, int b, int c, int d, \fBPieceType\fP promotion)"
.br
.ti -1c
.RI "string \fBreceive\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Network::Network (string s)"

.SS "Network::Network ()"

.SH "Member Function Documentation"
.PP 
.SS "string Network::receive ()"

.SS "void Network::send (int a, int b, int c, int d)"

.SS "void Network::send (int a, int b, int c, int d, \fBPieceType\fP promotion)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Chess-OOP from the source code\&.
