.TH "Point" 3 "Thu May 27 2021" "Version 2.0" "Chess-OOP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Point
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <enums_data\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int Point::x"

.SS "int Point::y"


.SH "Author"
.PP 
Generated automatically by Doxygen for Chess-OOP from the source code\&.
