.TH "Rook" 3 "Thu May 27 2021" "Version 2.0" "Chess-OOP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Rook
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rook\&.h>\fP
.PP
Inherits \fBPiece\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRook\fP (\fBColor\fP m_color)"
.br
.ti -1c
.RI "void \fBgenerateMoves\fP (\fBPoint\fP currentPos)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Rook::Rook (\fBColor\fP m_color)"

.SH "Member Function Documentation"
.PP 
.SS "void Rook::generateMoves (\fBPoint\fP currentPos)\fC [virtual]\fP"

.PP
Reimplemented from \fBPiece\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chess-OOP from the source code\&.
