.TH "sock_private.h" 3 "Thu May 27 2021" "Version 2.0" "Chess-OOP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sock_private.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBVER_STRING\fP   '1\&.0\&.0\&.0'"
.br
.ti -1c
.RI "#define \fBVER_MAJOR\fP   1"
.br
.ti -1c
.RI "#define \fBVER_MINOR\fP   0"
.br
.ti -1c
.RI "#define \fBVER_RELEASE\fP   0"
.br
.ti -1c
.RI "#define \fBVER_BUILD\fP   0"
.br
.ti -1c
.RI "#define \fBCOMPANY_NAME\fP   ''"
.br
.ti -1c
.RI "#define \fBFILE_VERSION\fP   '1\&.0\&.0\&.0'"
.br
.ti -1c
.RI "#define \fBFILE_DESCRIPTION\fP   'Developed using the Dev\-C++ IDE'"
.br
.ti -1c
.RI "#define \fBINTERNAL_NAME\fP   ''"
.br
.ti -1c
.RI "#define \fBLEGAL_COPYRIGHT\fP   ''"
.br
.ti -1c
.RI "#define \fBLEGAL_TRADEMARKS\fP   ''"
.br
.ti -1c
.RI "#define \fBORIGINAL_FILENAME\fP   ''"
.br
.ti -1c
.RI "#define \fBPRODUCT_NAME\fP   ''"
.br
.ti -1c
.RI "#define \fBPRODUCT_VERSION\fP   '1\&.0\&.0\&.0'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define COMPANY_NAME   ''"

.SS "#define FILE_DESCRIPTION   'Developed using the Dev\-C++ IDE'"

.SS "#define FILE_VERSION   '1\&.0\&.0\&.0'"

.SS "#define INTERNAL_NAME   ''"

.SS "#define LEGAL_COPYRIGHT   ''"

.SS "#define LEGAL_TRADEMARKS   ''"

.SS "#define ORIGINAL_FILENAME   ''"

.SS "#define PRODUCT_NAME   ''"

.SS "#define PRODUCT_VERSION   '1\&.0\&.0\&.0'"

.SS "#define VER_BUILD   0"

.SS "#define VER_MAJOR   1"

.SS "#define VER_MINOR   0"

.SS "#define VER_RELEASE   0"

.SS "#define VER_STRING   '1\&.0\&.0\&.0'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Chess-OOP from the source code\&.
